### ISSUE TITLE
Ver.0.4 ToDo

### ISSUE THREAD

**Issue by otoyo** [otoyo/astro-notion-blog#93]
- [x] Change blog index path to root 記事一覧をルートに変更
    - https://github.com/otoyo/astro-notion-blog/pull/92
    - https://github.com/otoyo/astro-notion-blog/pull/94
    - https://github.com/otoyo/astro-notion-blog/pull/98
- [x] Change font and adjust padding
    - https://github.com/otoyo/astro-notion-blog/pull/95
- [x] Display DB cover image to header DBカバー画像をヘッダーに表示
    - https://github.com/otoyo/astro-notion-blog/pull/96 
    - https://github.com/otoyo/astro-notion-blog/pull/99
- [x] Display DB icon to site name DBアイコンをサイト名に表示
    - https://github.com/otoyo/astro-notion-blog/pull/101
- [x] Align left site name サイト名を左寄せ
    - https://github.com/otoyo/astro-notion-blog/pull/97
- [x] Change link text style like Notion リンクテキストのスタイルをNotionライクに
    - https://github.com/otoyo/astro-notion-blog/pull/100
- [x] Change heading1, 2, 3 like Notion 見出し1, 2, 3のスタイルをNotionライクに
    - https://github.com/otoyo/astro-notion-blog/pull/102
- [x] Update README
    - https://github.com/otoyo/astro-notion-blog/pull/103
- [x] Support custom DB icon / DBアイコンでカスタムアイコンに対応する
    - https://github.com/otoyo/astro-notion-blog/pull/105
- [x] Copyボタンのテキストを数秒後に元に戻す
    - https://github.com/otoyo/astro-notion-blog/pull/106
- [x] Update package.json
    - https://github.com/otoyo/astro-notion-blog/pull/107
